run:
	PYTHONIOENCODING="UTF-8" python3 run.py

clean:
	rm -f ../benchmarks/Instantaneous*
	rm -f ../benchmarks/*.log
	rm -f ../benchmarks/*.init
	rm -f ../benchmarks/Temp*

parse:
	PYTHONIOENCODING="UTF-8" python3 parse_results.py

help:
	@echo	//////////////////////////////////////////////////
	@echo	//-----make	run   :	python3	run.py--------------//
	@echo	//-----make	clean :	rm -f ----------------------//
	@echo	//-----make	parse :	python3	parse_results.py----//
	@echo	//////////////////////////////////////////////////
	
